# See Docs at: https://lukasgeiter.github.io/mkdocs-awesome-nav/reference/

title: Community
preserve_directory_names: false
hide: false
flatten_single_child_sections: true
ignore: "*.hidden.md"

nav:
  - index.md
  - For Students: students.md
  - Collaborate: collaborate.md
  - Contact Us: contact.md

append_unmatched: false